config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'main#index'
  post 'create', to: 'main#create_tweet', as: 'create_tweet'
  post 'like/:tweet', to: 'main#like_tweet', as: 'like_tweet'
  post 'unlike/:tweet', to: 'main#unlike_tweet', as: 'unlike_tweet'
  post 'retweet/:tweet', to: 'main#retweet', as: 'retweet'
  get 'show/:tweet', to: 'main#show', as: 'show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :tweet
  belongs_to :user
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  belongs_to :original, class_name: 'Tweet', foreign_key: 'tweet_id', optional: true
  has_many :likes
  paginates_per 50

  validates_presence_of :content
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  

  validates_presence_of :profile_img_url

  has_many :tweets
  has_many :likes

  protected

  def serializable_hash(options = nil)
    super(options).merge(profile_img_url: profile_img_url)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_devise_params, if: :devise_controller?
  
  protected

  def configure_devise_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:profile_img_url])
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
    @tweets = Tweet.order(created_at: 'desc').page(params[:page])
    @user_likes = Like.where(user_id: current_user.id).pluck(:tweet_id)
  end

  def show
    @tweet = Tweet.find(params[:tweet])
    @user_likes = Like.where(user_id: current_user.id).pluck(:tweet_id)
  end

  def create_tweet
    logger.info(@user_likes)
    @tweet = Tweet.new
    @tweet.content = params[:content]
    @tweet.user = current_user
    if @tweet.save
      flash[:notice] = 'Tweet sent!'
      redirect_to :root
    else
      @tweets = Tweet.order(created_at: 'desc').page(params[:page])
      flash[:alert] = 'Content is mandatory'
      render :index
    end
  end

  def like_tweet
    @tweet = Tweet.find(params[:tweet])
    @like = Like.new
    @like.tweet = @tweet
    @like.user = current_user
    @like.save
    flash[:notice] = "Tweet liked!"
    redirect_to :root
  end

  def unlike_tweet
    @like = Like.where(user_id: current_user.id).where(tweet_id: params[:tweet]).first
    @like.destroy
    flash[:notice] = "Tweet unliked!"
    redirect_to :root
  end

  def retweet
    @original = Tweet.find(params[:tweet])
    @tweet = Tweet.new
    @tweet.content = @original.content
    @tweet.user = current_user
    @tweet.tweet_id = @original.id
    @tweet.save
    @original.retweets = @original.retweets + 1
    @original.save
    flash[:notice] = 'Tweet retweeted!'
    redirect_to :root
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/layouts/_login_bar.html.erb
<div class="text-right">
  <% if user_signed_in? %>
    <%= current_user.email %> | <%= link_to "Logout", destroy_user_session_path, { method: :delete } %>
  <% else %>
    <%= link_to 'Login', new_user_session_path %> |
    <%= link_to 'Sign up', new_user_registration_path %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProyectoTwitter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!-- Bootstrap -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    <!-- End Bootstrap -->
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <div class="container">
      <%= render 'layouts/login_bar' %>
      <% if flash[:notice] %>
      <div class="alert alert-success" role="alert">
        <%= flash[:notice] %>
      </div>
      <% end %>
      <% if flash[:alert] %>
      <div class="alert alert-danger" role="alert">
        <%= flash[:alert] %>
      </div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/main/index.html.erb
<h1>Proyecto Twitter</h1>
<hr>

<% if user_signed_in? %>
<h4>Escribir un tweet</h4>
<%= form_tag create_tweet_path, method: :post do %>
<%= text_area_tag 'content' %>
<%= submit_tag 'Submit' %>
<% end %>
<hr>
<% end %>

<% if @tweets.count > 0 %>

<% @tweets.each do |tweet| %>
<div class="tweet" id="tweet-<%= tweet.id %>%">
  <p><%= image_tag tweet.user.profile_img_url, class: 'user-thumb' %> <%= tweet.user.email %></p>
  <div class="content">
    <%= tweet.content %>
  </div>
  <% if !tweet.original.nil? %>
    <p><em><%= link_to 'Ver tweet original', show_path(tweet: tweet.original.id)%></em></p>
  <% end %>
  <% if user_signed_in? %>
  <p>
    <% if @user_likes.include? tweet.id %>
    <%= link_to 'Unike', unlike_tweet_path(tweet: tweet.id), method: :post %>
    <% else %>
    <%= link_to 'Like', like_tweet_path(tweet: tweet.id), method: :post %>
    <% end %> |
    <%= link_to 'Retweet', retweet_path(tweet: tweet.id), method: :post %>
  </p>
  <% end %>
  <p><%= link_to (time_ago_in_words tweet.created_at), show_path(tweet: tweet.id) %> | <strong>Likes:</strong> <%= tweet.likes.count %> | <strong>Retweets:</strong> <%= tweet.retweets.blank? ? 0 : tweet.retweets %></p>
</div>
<hr>
<% end %>
<%= paginate @tweets %>

<% else %>
<p><em>No hay tweets</em></p>
<% end %>

app/views/main/show.html.erb
<div class="tweet" id="tweet-<%= @tweet.id %>%">
  <p><%= image_tag @tweet.user.profile_img_url, class: 'user-thumb' %> <%= @tweet.user.email %></p>
  <div class="content">
    <%= @tweet.content %>
  </div>
  <% if !@tweet.original.nil? %>
    <p><em><%= link_to 'Ver tweet original', show_path(tweet: @tweet.id)%></em></p>
  <% end %>
  <p><%= time_ago_in_words @tweet.created_at %> | <strong>Likes:</strong> <%= @tweet.likes.count %> | <strong>Retweets:</strong> <%= @tweet.retweets.blank? ? 0 : @tweet.retweets %></p>
  <div class="likes">
    <% @tweet.likes.each do |like| %>
    <%= image_tag like.user.profile_img_url, class: 'small-list', title: like.user.email %>
    <% end %>
  </div>
</div>
<hr>
<%= link_to '< Atrás', 'javascript:history.go(-1)' %>